version: "3.8"

services:
  secret-service:
    image: muditshukla3/spring-boot-rest-client:0.0.1-RELEASE
    ports:
      - "7070:7070"
      - "7071:7071" # This is for spring boot actuator
    environment:
      - SPRING_ACTIVE_PROFILES: "dev"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback
        monitor: 60s
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 30s
    healthcheck:
      test: if [ ! `wget -qO- http://localhost:7071/manage/health 2>/dev/null | jq . | jq --exit-status '.status == "UP"'` ]; then exit 1; fi
      interval: 30s
      timeout: 45s
      retries: 3
      start_period: 30s